services:
  backend-arbtrader:
    image: ghcr.io/lucasmelloleao/backend-arbtrader:latest
    pull_policy: always
    container_name: backend-arbtrader
    network_mode: "host"
    command: pm2-runtime ecosystem.config.js
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MASTER_PASSWORD=${MASTER_PASSWORD}
    mem_limit: 4g
    memswap_limit: 4g
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

